version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:9.4
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
