version: '3.7'
services:

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/app:/app
      - /tmp/market_navigator_data:/market_navigator_data
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
    entrypoint: /start-reload.sh

  postgres:
    container_name: postgres
    image: postgres:9.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"

  analysis:
    container_name: analysis
    build:
      context: ./analysis
      dockerfile: Dockerfile
    volumes:
      - ./analysis/src:/usr/src/app
      - /tmp/market_navigator_data:/market_navigator_data
    restart: always
    environment:
      ENVIRONMENT: "dev"
    tty: true
    entrypoint: /bin/bash
