version: '3.7'
services:

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/app:/app
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"

  postgres:
    container_name: postgres
    image: postgres:9.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
