apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "0 0 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: registry.digitalocean.com/market-navigator-registry/market_navigator_api:latest
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
