apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: analysis
  labels:
    job: analysis
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Forbid"
  suspend: true
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: src-pv-storage
              persistentVolumeClaim:
                claimName: src-pv-claim
          containers:
            - name: market-state
              image: gcr.io/market-navigator-281018/market_navigator_analysis:latest
              command: ["python",  "per_high_low.py"]
              volumeMounts:
                - name: local-src
                  mountPath: /usr/src/app/
          volumes:
            - name: local-src
              hostPath:
                path: /src/analysis/src
