apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: analysis
  labels:
    job: analysis
spec:
  ## Weekly cron schedule. Change to daily once I upgrade to a paid plan.
  schedule: "0 0 * * 0"
  concurrencyPolicy: "Forbid"
  suspend: true
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        # metadata:
        #   labels:
        #     gcp-auth-skip-secret: "true"
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: local-src
              hostPath:
                path: /src/analysis/src
          containers:
            - name: market-state
              image: gcr.io/market-navigator-281018/market_navigator_analysis:latest
              env:
              - name: IEX_LOG_LEVEL
                value: "DEBUG"
              - name: ENVIRONMENT
                value: "DEV"
              imagePullPolicy: IfNotPresent
              command: [ "/bin/bash", "-c", "--" ]
              args: [ "sleep 15; nohup python per_high_low.py" ] ## Sleep is added to allow gcsfuse sufficient time to configure.
              # args: [ "while true; do sleep 30; done;"]
              volumeMounts:
                - name: local-src
                  mountPath: /usr/src/app/
              securityContext:
                privileged: true
                capabilities:
                  add:
                    - SYS_ADMIN
              lifecycle:
                postStart:
                  exec:
                    command: ['gcsfuse', '-o', 'allow_other', 'market-navigator-data', '/data/market_navigator/static_data']
                    # For debugging: gcsfuse -o allow_other -o nonempty --foreground --debug_fuse market-navigator-data /data/market_navigator/static_data
                preStop:
                  exec:
                    command: ['fusermount', '-u', '/data/market_navigator/static_data']
