apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: src-pv-storage
          persistentVolumeClaim:
            claimName: src-pv-claim
      containers:
      - name: api
        image: gcr.io/market-navigator-281018/market_navigator_api:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: src-pv-storage
            mountPath: /usr/src/app
            subPath: api/src
        env:
        - name: PORT
          value: "8080"
